import { Carrois_Gothic } from "next/font/google";
import "./globals.css";
import CartDrawer from "../components/CartDrawer/CartDrawer";
import Navbar from "@/components/Navbar";
import Footer from "../components/Footer";
import ReduxWrapper from "../components/ReduxWrapper/ReduxWrapper";
import ProtectedRoutes from "@/components/ProtectedRoutes/ProtectedRoutes";
import AosWrapper from "../components/AosWrapper";
import { Toaster } from "react-hot-toast";
import Head from "next/head";

const carrois = Carrois_Gothic({
  variable: "--font-carrois",
  subsets: ["latin"],
  weight: "400",
});
export const metadata = {
  title: "Refilly -- Online T-shirt Mart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        {/* <link
          href="https://fonts.googleapis.com/css2?family=Carrois+Gothic&display=swap"
          rel="stylesheet"
        /> */}
      </Head>
      <body className={` ${carrois.variable} antialiased`}>
        {/* <AuthProvider> */}
        {/* <ProductProvider> */}
        <ReduxWrapper>
          <AosWrapper />
          <Navbar />
          {children}
          <Footer />
          <CartDrawer />
          <ProtectedRoutes />
        </ReduxWrapper>
        <Toaster position="bottom-right" />
      </body>
    </html>
  );
}
