// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import { ProductProvider } from "@/context/ProductContext";
// import { AuthProvider } from "@/context/AuthContext";
import CartDrawer from "@/components/CartDrawer";
// import AuthModal from "@/components/AuthModal";
import Navbar from "@/components/Navbar";
import Footer from "../components/Footer";
import ReduxWrapper from "../components/ReduxWrapper/ReduxWrapper";
import ProtectedRoutes from "@/components/ProtectedRoutes/ProtectedRoutes";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Refilly -- Online T-shirt Mart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  console.log(process.env.NEXT_PUBLIC_SERVER);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <AuthProvider> */}
        {/* <ProductProvider> */}
        <ReduxWrapper>
          <Navbar />
          {children}
          <Footer />
          <CartDrawer />
          <ProtectedRoutes />
        </ReduxWrapper>
        {/* <AuthModal /> */}
        {/* </ProductProvider> */}
        {/* </AuthProvider> */}
        <Toaster position="bottom-right" />
      </body>
    </html>
  );
}
